In [ ]:
import numpy as np

## 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [3]:
import numpy as np
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
import numpy as np
l = [1, 2, 0, 0, 4, 0]
z = np.array(l)
l_new = list(np.nonzero(z)[0]) 
print(l_new)

[0, 1, 4]


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [9]:
import numpy as np
z = np.random.random((10,10))
print(z) 
zmin, zmax = z.min(), z.max()
print("Minimum and Maximum Values: ")
print(zmin, zmax)

[[0.09787938 0.45152473 0.95204482 0.91353571 0.63772748 0.11406457
  0.00944548 0.9750989  0.09958424 0.82034234]
 [0.41809955 0.10195002 0.33647193 0.79058661 0.48328013 0.08508407
  0.8543568  0.93171962 0.16593694 0.41008203]
 [0.96581885 0.71171951 0.33609951 0.65744624 0.07216833 0.24760438
  0.16162517 0.80135783 0.45350255 0.94839304]
 [0.00852767 0.71272771 0.43318611 0.52481702 0.0169153  0.79445481
  0.818685   0.20786132 0.49326489 0.07795037]
 [0.54354374 0.25740791 0.59306176 0.01662121 0.83788422 0.78560932
  0.17101139 0.94578753 0.4316447  0.90677215]
 [0.30656556 0.12580596 0.38830657 0.91377271 0.19463296 0.13254636
  0.49078118 0.95078635 0.37933138 0.90920099]
 [0.93910286 0.04228358 0.38293637 0.57805101 0.11934057 0.68720497
  0.7218413  0.72041657 0.95121087 0.31790277]
 [0.02457813 0.4371649  0.31376637 0.53094886 0.11132491 0.0419212
  0.60195448 0.45382867 0.35513021 0.21133492]
 [0.33829294 0.70154437 0.91459359 0.61493876 0.26528576 0.21559717
  0.2955451  

## 6. Create a random vector of size 30 and find the mean value.

In [13]:
z = np.random.random(30)
m =z.mean()
print(m)

0.49161850410642843
